import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Week-TodoList",
  description: "Generated by Ahmed & Abdo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${inter.className} bg-light-gray `}>{children}</body>
    </html>
  );
}
